Parameters:
  DynamoTableArn:
    Type: String

AWSTemplateFormatVersion: '2010-09-09'
Description: Allows Lambda functions to call AWS services on your behalf

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-iam-role.html#cfn-iam-role-managedpolicyarns
  CoffeeShopRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: LamdaRule
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
              # https://docs.aws.amazon.com/lambda/latest/dg/lambda-intro-execution-role.html
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      # https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html
      # https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html
      # https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AWSLambdaBasicExecutionRole.html
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Sid: DescribeQueryScanCoffeeTable
                Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource: !Ref DynamoTableArn
          PolicyName: DynamoDB-Policy
      Path: "/"
      
  # The contents authorize API Gateway to invoke a backend Lambda function.
  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - apigateway.amazonaws.com
      Policies:
        - PolicyName: !Sub "ApiGatewayRole-InvokeFunctionPolicy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !ImportValue LambdaGetFunctArn
  
Outputs:
  CoffeeShopRoleArn:
    Description: Execution role ARN for Lambda
    Value: !GetAtt CoffeeShopRole.Arn
  ApiGatewayRole:
    Description: Role for API Gateway to invoke Lambda functions
    Value: !GetAtt ApiGatewayRole.Arn
